#+title: Laboratório 1

* Conteúdo programático

- instalação e configuração das ferramentas do curso
- praticando o uso da linha de comando
- compilando programas C
- usando Git para controle de versão

* Objetivos

1. Configurar o ambiente de desenvolvimento
2. Praticar o uso das ferramentas: linha de comando, editor e
   compilador
3. Familiarização com o fluxo básico de trabalho com Git e GitHub

* Atividade 1: instalação das ferramentas

Como alternativa à instalação local, é possível usar o [[https://github.com/features/codespaces?locale=pt-BR][GitHub
Codespaces]] diretamente no navegador (veja as notas da aula 03) ou o
[[https://replit.com/][Replit]], outro ambiente Linux acessível pelo navegador sem necessidade
de instalação local.

** Usuários Windows: instalar o WSL

Antes de instalar as demais ferramentas, usuários Windows precisam
instalar o WSL (Windows Subsystem for Linux), que permite rodar um
ambiente Linux dentro do Windows. Consulte as notas da aula 03 para
mais detalhes.

No PowerShell (como administrador):

#+begin_src bash
wsl --install
#+end_src

Documentação oficial:
https://learn.microsoft.com/pt-br/windows/wsl/install

*** Possível problema com virtualização

Após reiniciar o Windows, caso apareça um erro relacionado à
virtualização, você deve habilitar a opção de virtualização na BIOS do
computador. Para isso, desligue o computador e pressione a tecla para
abrir a BIOS ao ligá-lo (normalmente a tecla "Delete" ou "F2",
dependendo da placa-mãe). Procure a opção *SVM Mode* (AMD) ou *Intel
Virtualization Technology* (Intel) e habilite-a. Após isso, recomece
o processo de instalação do WSL.

** Instalar o Git

*** Linux (ou WSL)

#+begin_src bash
sudo apt update && sudo apt install git
#+end_src

Documentação:
https://learn.microsoft.com/pt-br/windows/wsl/tutorials/wsl-git

*** MacOS

O Git já vem pré-instalado no MacOS. Para verificar:

#+begin_src bash
git --version
#+end_src

Caso não esteja instalado, o sistema oferecerá a instalação automática
via Xcode Command Line Tools. Recomendo o uso no Mac do
https://brew.sh e com ele instalação de versão mais atualizada do Git.

** Instalar o compilador C

*** Linux (ou WSL)

#+begin_src bash
sudo apt update && sudo apt install build-essential
#+end_src

O pacote =build-essential= inclui o =gcc=, o =make= e outras
ferramentas necessárias. Opcionalmente, instale também o =clang=:

#+begin_src bash
sudo apt install clang
#+end_src

Referência: https://phoenixnap.com/kb/install-gcc-ubuntu

*** MacOS

Instale o Xcode Command Line Tools:

#+begin_src bash
xcode-select --install
#+end_src

Isso instalará o =clang= (compilador C padrão no MacOS) e o =make=.
O =gcc= no MacOS é na verdade um alias para o =clang=, o que é
suficiente para o curso.

** Instalar o VS Code

Baixe e instale o VS Code em https://code.visualstudio.com/.

*** Detalhes para usuários Windows

- Instale o VS Code no Windows (não dentro do WSL).
- Durante a instalação, marque a opção *Adicionar ao PATH*.
- Após a instalação, instale a extensão [[https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack][Remote Development]], que
  inclui a integração com o WSL. Com ela, o VS Code consegue abrir
  projetos dentro do ambiente Linux do WSL.

*** Extensão para C/C++

Para todos os sistemas, instale a extensão [[https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools][C/C++]] no VS Code, que
oferece syntax highlighting, autocompletar e integração com o
compilador.

* Atividade 2: tutorial da linha de comando

Fazer o tutorial interativo
https://github.com/JulianEducation/CommandLineBasics

* Atividade 3: praticando a linha de comando

Depois de completar o tutorial, pratique os comandos em seu
terminal. Antes de começar, clone o repositório do curso:

#+begin_src bash
$ git clone https://github.com/emap-20261-ic/syllabus.git
#+end_src

1. Identifique o diretório corrente com =pwd=.

2. Mude o diretório atual com =cd= para o diretório onde o =syllabus=
   foi clonado. Navegue até =semana-1/lab= usando caminhos relativos e
   absolutos.

3. Crie um arquivo texto com o nome =lab1.txt= usando =touch= e =cat=
   (com redirecionamento; finalize a entrada com Ctrl-D; Ctrl-C
   interrompe o comando).

4. Crie um novo diretório chamado =tmp1= com =mkdir= e mova o arquivo
   criado no passo anterior para esse diretório com =mv=.

5. Copie o diretório =tmp1= para =tmp2= usando =cp -r= (cópia
   recursiva). Consulte a página =man cp=.

6. Explore o histórico de comandos com =history=, use TAB para
   auto-completar, setas para cima/baixo para navegar no histórico e
   =!NUM= para repetir comandos.

7. Liste o conteúdo de um diretório com =ls=. Passe os parâmetros
   =-l= e =-lh= e entenda a diferença.

8. Redirecione a saída do =ls= para um arquivo no =tmp1=.

9. Encontre todos os arquivos em um diretório que correspondem a um
   padrão específico usando =find= e =xargs=. Por exemplo, mude para
   o diretório =syllabus= e execute:

   #+begin_example
   $ find . -name '*.pdf' | xargs file
   #+end_example

10. Exiba o conteúdo de um arquivo de texto com =cat=, =less=, =tail=
    e =head=. Conte linhas com =wc=.

11. Filtre linhas específicas de um arquivo com =grep=. Use =sort= e
    =uniq=:

    #+begin_example
    $ grep -rh "include" *.c | sort | uniq -c
      2 #include <ctype.h>
      1 #include <math.h>
     39 #include <stdio.h>
    #+end_example

12. Experimente o sequenciamento de comandos. Assumindo que não exista
    o arquivo =lixo= no diretório:

    #+begin_example
    $ ls ; echo $?
    $ rm lixo; echo $?

    $ rm lixo && echo 1
    $ rm lixo || echo 1
    #+end_example

13. Monitore o uso de recursos do sistema com =top= e =ps=.
    Experimente também =who=, =whoami= e =df=.

* Atividade 4: compilando um programa em C

Nesta atividade vamos usar o repositório do =assignment-00= para
compilar e executar um programa em C.

1. Clone o seu repositório do =assignment-00=. Lembre-se de que cada
   aluno tem seu próprio repositório criado pelo GitHub Classroom.
   Acesse a organização do curso no GitHub para encontrar o seu:

   #+begin_src bash
   $ git clone <url-do-seu-repositorio-assignment-00>
   $ cd assignment-00
   #+end_src

2. Examine os arquivos do repositório com =ls= e leia o conteúdo do
   arquivo =test.c= com =cat=.

3. Compile o arquivo =test.c= de diferentes formas:

   #+begin_example
   $ clang test.c -Wall
   $ clang test.c -Wall -o test
   $ make test
   #+end_example

   A flag =-Wall= habilita todos os avisos do compilador, o que ajuda
   a identificar problemas no código. A flag =-o= define o nome do
   arquivo executável de saída.

4. Execute o programa compilado:

   #+begin_example
   $ ./test
   #+end_example

5. Abra o arquivo =test.c= no editor, faça uma modificação (por
   exemplo, altere uma mensagem) e compile novamente. Verifique que a
   mudança aparece na execução.

6. Experimente também compilar com o =gcc=:

   #+begin_example
   $ gcc test.c -Wall -o test
   #+end_example

* Atividade 5: usando o Git

Nas atividades anteriores, você já usou o Git para clonar
repositórios. Agora vamos praticar a criação de um repositório
local. Vá para outra pasta de seu computador, fora do syllabus.

1. Crie um repositório local do zero:

   #+begin_src bash
   $ mkdir teste-git
   $ cd teste-git
   $ git init
   #+end_src

   Observe que o Git criou um diretório oculto =.git/=, onde ele
   armazena todo o histórico do repositório.

2. Crie um arquivo e faça o primeiro commit:

   #+begin_src bash
   $ touch readme.txt
   $ git add readme.txt
   $ git commit -m "primeiro commit"
   #+end_src

3. Edite o arquivo =readme.txt= (adicione algum texto) e observe o
   estado do repositório:

   #+begin_src bash
   $ git status
   $ git diff
   #+end_src

4. Salve esta nova versão em um commit:

   #+begin_src bash
   $ git add readme.txt
   $ git commit -m "primeira edição"
   #+end_src

5. Faça mais uma edição e outro commit. Depois examine o histórico:

   #+begin_src bash
   $ git log
   #+end_src

   A saída mostrará todos os commits, do mais recente para o mais
   antigo, cada um com seu identificador (hash), autor, data e
   mensagem.

6. Experimente voltar no tempo usando o hash de um commit anterior:

   #+begin_src bash
   $ git checkout <hash-do-commit>
   #+end_src

   Leia com atenção a mensagem que o Git irá exibir. Para voltar ao
   estado mais recente:

   #+begin_src bash
   $ git checkout main
   #+end_src

Para saber mais sobre Git: https://git-scm.com/doc
