#+title: half

* objetivos

- trabalhar com diferentes tipos de dados
- praticar conversão de tipos
- usar operações matemáticas
- criar uma função com parâmetros de entrada e valor de retorno
  
* contexto

Suponha que você esteja comendo em um restaurante com um amigo e
queira dividir a conta igualmente. Você pode querer antecipar o valor
que deve antes que a conta chegue com o imposto adicionado. Neste
problema, você completará uma função para calcular o valor que cada um
de vocês deve com base no valor da conta, do imposto e da gorjeta.

* detalhes para implementação

Sua função deve usar os parâmetros de entrada, bill (total), tax
(imposto) e tip (gorgeta), para calcular o valor que cada pessoa deve
pagar. No entanto, como esses valores são porcentagens, você terá que
fazer algum trabalho para convertê-los em formatos mais apropriados
para usar em seu cálculo.

O imposto deve ser adicionado ao valor da conta antes de calcular a
gorjeta. Por fim, você devolverá exatamente a metade do valor total,
incluindo o valor da conta, o imposto e a gorjeta.

* pergunta

Por que você acha que existem diferentes tipos de dados em C?

* testando

#+begin_example
$ ./half
bill total: 12.50
tax percent: 8.875
tip percent: 20
individual amount: $8.17

$ ./half
bill total: 23.50
tax percent: 7
tip percent: 15
individual amount: $14.46

$ ./half
bill total: 100
tax percent: 6.25
tip percent: 18
individual amount: $62.69
#+end_example
