#+title: password

Como sabemos, é importante usarmos senhas que não sejam
triviais. Vários aplicativos e sites exigem senhas que não tenham
apenas caracteres alfabéticos, mas também tenham números e símbolos.

Neste projeto, o usuário irá passar uma senha. O programa então irá
validar a senha usando a função =check= que você irá completar.

Se a senha contiver pelo menos um caractere maiúsculo, um caractere
minúsculo, um número e um símbolo (qualquer símbolo printável
=![]();#@/\+--$%&*?.<>,;:= que não seja uma letra do alfabeto) a
função deve retornar true. Caso contrário, false.

* demo

Seu programa deve ser comportar da seguinte maneira:

#+begin_example
% ./a.out
Entre sua senha (sem espaços): hello
Sua senha é fraca! Tente novamente.

% ./a.out
Entre sua senha (sem espaços): h3ll(
Sua senha é fraca! Tente novamente.

% ./a.out
Entre sua senha (sem espaços): h3LL0!
Sua senha é forte! Parabéns!
#+end_example

* detalhes

Sua função irá iterar através da senha que é fornecida pelo
usuário. Como você precisa encontrar pelo menos uma letra minúscula,
uma letra maiúscula, um número e um símbolo, convém criar uma variável
booleana para cada condição e definir cada variável como =false= antes
de iterar na string. Se você encontrar um número, por exemplo, pode
definir a variávbel booleana que indica presença de número como
=true=. Se todos os booleanos forem verdadeiros no final da função,
isso significa que todos os critérios foram atendidos e você
retornaria =true=. Talvez você possa otimizar ainda. Você pode
determinar que todas as condições foram satisfeitas antes de terminar
de verificar todos os caracteres da string. Finalmente, você pode
armazenar em uma única variável vários bits. E pode usar [[https://en.wikipedia.org/wiki/Bitwise_operations_in_C][operações
bitwise]].

dicas:

- a biblioteca =ctype= tem algumas funções muito úteis para
  identificar o tipos de caracteres.

- variáveis booleanas podem ser usadas para armazenar critérios para
  execução dos programas.
  
