#+title: password

Como sabemos, é importante usarmos senhas que não sejam
triviais. Vários aplicativos e sites exigem senhas que não tenham
apenas caracteres alfabéticos, mas também tenham números e símbolos.

Neste projeto, o usuário irá passar uma senha. O programa então irá
validar a senha usando a função =valid= que você irá completar.

Se a senha contiver pelo menos um caractere maiúsculo, um caractere
minúsculo, um número e um símbolo (qualquer símbolo printável
=![]();#@/\+--$%&*?.<>,;:= que não seja uma letra do alfabeto) a
função deve retornar true. Caso contrário, false.

* demo

Seu programa deve ser comportar da seguinte maneira:

#+begin_example
% ./a.out
Enter your password (no spaces): hello
Weak password! Try again.

% ./a.out
Enter your password (no spaces): h3ll(
Weak password! Try again.

% ./a.out
Enter your password (no spaces): h3LL0!
Strong password!
#+end_example

* detalhes

Sua função irá iterar através da senha que é fornecida pelo
usuário. Como você precisa encontrar pelo menos uma letra minúscula,
uma letra maiúscula, um número e um símbolo, convém criar uma variável
booleana para cada condição e definir cada variável como =false= antes
de iterar na string. Se você encontrar um número, por exemplo, pode
definir a variável booleana que indica presença de número como
=true=. Se todos os booleanos forem verdadeiros no final da função,
isso significa que todos os critérios foram atendidos e você
retornaria =true=. Talvez você possa otimizar ainda. Você pode
determinar que todas as condições foram satisfeitas antes de terminar
de verificar todos os caracteres da string. Finalmente, você pode
armazenar em uma única variável vários bits. E pode usar [[https://en.wikipedia.org/wiki/Bitwise_operations_in_C][operações
bitwise]].

* a biblioteca =<ctype.h>=

A biblioteca padrão =<ctype.h>= oferece funções para classificar
caracteres. Cada função recebe um =int= (o código ASCII do caractere)
e retorna um valor não-zero se a condição for verdadeira, zero caso
contrário. Você já viu =isdigit= em sala de aula (=mario3.c=). As
demais seguem o mesmo padrão:

| função       | verdadeiro quando...                    |
|--------------+-----------------------------------------|
| =isupper(c)= | =c= é letra maiúscula (A–Z)             |
| =islower(c)= | =c= é letra minúscula (a–z)             |
| =isdigit(c)= | =c= é dígito (0–9)                      |
| =isalpha(c)= | =c= é letra                             |
| =isalnum(c)= | =c= é letra ou dígito                   |
| =isgraph(c)= | =c= é caractere imprimível (não espaço) |

Uso típico:

#+begin_src c
#include <ctype.h>

if (isupper(c))
    // c é maiúscula
#+end_src

* dicas

- use as funções de =<ctype.h>= para classificar cada caractere da
  senha.

- variáveis booleanas podem ser usadas para registrar se cada
  critério já foi satisfeito.
  
