#+title: snackbar

* descrição

Imagine que você está na praia e deseja pedir vários itens da
lanchonete. Você tem uma quantia limitada de dinheiro e deseja obter
um custo total para seus itens antes de fazer o pedido.

No =snackbar.c= você completará a função =get_total=.  Ela deverá
implementar um algoritmo de pesquisa linear para pesquisar cada item
recebido das linhas da entrada (no exemplo abaixo passadas por um
arquivo) e retornar o valor total do pedido.

#+begin_example
% ./snackbar menu.txt < pedido0.txt
Read 13 items from the menu:
- burger: 9.50
- vegan burger: 11.00
- hot dog: 5.00
- cheese dog: 7.00
- fries: 5.00
- cheese fries: 6.00
- cold pressed juice: 7.00
- cold brew: 3.00
- water: 2.00
- soda: 2.00
- misto quente: 5.00
- copo de leite: 4.00
- cerveja: 5.00

>> total cost: $12.00
#+end_example

Veja o conteúdo e o formato dos arquivos =menu.txt= e
=pedido0.txt=.

No arquivo =menu.txt=, a primeira linha especifica a quantidade de
itens no menu. As linhas seguintes são os itens, strings que podem
conter espaço são os nomes dos itens. O ":" separa os nomes dos
valores (float) de cada item.

* detalhe

A função =main= já está completa. Leia o código presente no arquivo
para familiarizar-se com a estrutura geral. A função
=read_items_from_file= lê o arquivo =menu.txt= que estiver no mesmo
diretório do programa. Você pode remover ou adicionar itens do
=menu.txt= para testar.

A função =read_items_from_file_1= não é usada, mas seria uma
implementação alternativa de =read_items_from_file=. Você consegue
identificar a diferença?

A função =get_total= recebe o array de itens (menu) e o número de
itens no menu. Ela deve ler as linhas da entrada padrão (STDIN) até
encontrar uma linha cujo valor seja =END=. Para cada linha, a função
irá primeiro converter em minúsculas (veja como menu é lido) e
realizar uma busca linear no array com o menu. Ao encontrar o item no
menu, deve somar seu valor ao total do pedido. A função então retorna
o total do pedido após ler todas as linhas da entrada.

Você pode ignorar os pedidos de nomes que não forem encontrados no
menu.

* pergunta

Por que um array de estruturas é uma solução melhor aqui do que vários
arrays?
